---
apiVersion: test.openstack.org/v1beta1
kind: TrexPerformance
metadata:
  name: performance-tests
  namespace: openstack
spec:
  workloadSSHKeySecretName: 'open-tofu-ssh-keys'
  debug: true
  stepName: trex
  containerImage: quay.io/rhos-dfg-nfv/test_performance:latest
  AnsibleGitRepo: https://github.com/eshulman2/ansible-nfv.git
  ansibleInventory: |
    all:
      children:
        controllers:
          vars:
        ocps:
          vars:
    localhosts:
      hosts:
        localhost:
          ansible_connection: local
    controllers:
      hosts:
        controller-0:
          ansible_host: 192.168.201.9
          ansible_user: zuul
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_ssh_private_key_file: ~/.ssh/id_cifw
    ocps:
      hosts:
        ocp-0:
          ansible_host: 192.168.201.10
          ansible_user: core
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_ssh_private_key_file: ~/.ssh/devscripts_key
        ocp-1:
          ansible_host: 192.168.201.11
          ansible_user: core
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_ssh_private_key_file: ~/.ssh/devscripts_key
        ocp-2:
          ansible_host: 192.168.201.12
          ansible_user: core
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_ssh_private_key_file: ~/.ssh/devscripts_key
  ansibleExtraVars: ' -e manual_run=false -e binary_perf_log=/tmp/dpdk_performance.log -e dut_group=dpdk_dut -e dut_type=dpdk -e testpmd_lcores=3,4,5 -e trex_rate=2 -e emc_insert_inv_prob=100 -e clone_traffic_gen_repo=false -e private_key_fetch_location=~/ '
  ansibleVarFiles: |
    ---
    # Use exist cloud resources
    cloud_resources: external
    # DUT compute
    dut_compute: compute-1
    # Trex config
    trex_lcores: "2-11"
    # testpmd path (for rhel 8.4 vm)
    testpmd_bin: "/root/dpdk/build/app/dpdk-testpmd"
    # Disable search rates higher than the specified
    binary_search_disable_upward_search: true
    # Used to balance queues
    binary_search_warmup_trial_runtime: 120
    discover_instance_external_ip: true
    ssh_key: test_keypair.key
    dynamic_instances:
      - name: trex
        group: trex
        user: cloud-user
      - name: testpmd-dpdk-dut
        group: dpdk_dut
        user: cloud-user
      - name: testpmd-sriov-vf-dut
        group: sriov_dut
        user: cloud-user
